#※※※※※※※※※※※※Server※※※※※※※※※※※※
server:
  port: 80
  tomcat:
    url-encoding: UTF-8
  servlet:
    context-path: #项目路径

#※※※※※※※※※※※※SpringBoot基础配置※※※※※※※※※※※※
spring:
  # MVC 配置
  mvc:
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    #不要为我们工程中的资源文件建立映射
    add-mappings: false
  #※※※Ehcache缓存配置※※※
  cache:
    #配置ehcache缓存名
    type: 'ehcache'
    ehcache:
      #指定ehcache配置文件路径
      config: 'classpath:ehcache.xml'
  #配置thymeleaf 官方推荐模板引擎
  thymeleaf:
    prefix: 'classpath:/views/'
    suffix: '.html'
    mode: 'HTML'
    encoding: 'UTF-8'
    content-type: 'text/html'
    cache: false # 开发阶段务必关闭缓存
  #※※※Redis缓存服务器※※※
  redis:
    database: 0 #Redis数据库索引（默认为0）
    host: 'localhost' #Redis服务器地址
    port: 6379 #Redis服务器连接端口 
    password: '' #Redis服务器连接密码（默认为空）
    pool:
      max-active: 200 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接 
    timeout: 1000 #连接超时时间（毫秒）
  velocity:
    content-type: 'application/json'

#※※※※※※※※※※※※Mybatis※※※※※※※※※※※※
mybatis:
  type-aliases-package: com.qm.code.entity # 指定实体类包路径
  mapper-locations:
    - 'classpath*:**/*Mapper.xml' # 该行配置请勿修改
  configuration:
    map-underscore-to-camel-case: true #是否启动数据库下划线自动映射实体
    auto-mapping-behavior: full # resultMap 自动映射级别设置

#※※※※※※※※※※※※ PageHelper 分页插件 ※※※※※※※※※※※※
pagehelper:
  # helperDialect 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。 你可以配置helperDialect属性来指定分页插件使用哪种方言。配置时，可以使用下面的缩写值：
  # oracle,mysql,mariadb,sqlite,hsqldb,postgresql,db2,sqlserver,informix,h2,sqlserver2012,derby
  helperDialect: mysql
  # reasonable 分页合理化参数，默认值为false。
  # 当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。
  # 默认false 时，直接根据参数进行查询。
  reasonable: true
  # supportMethodsArguments 支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  supportMethodsArguments: true
  # params为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero。
  params: count=countSql
  # 默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）。
  page-size-zero: true

#※※※※※※※※※※※※Logger※※※※※※※※※※※※
logging:
  config: 'classpath:logback-spring.xml'