#※※※※※※※※※※※※Server※※※※※※※※※※※※
server:
  port: 80
  tomcat: 
      url-encoding: UTF-8
  servlet: 
    session: 
      timeout: 60
#※※※※※※※※※※※※SpringBoot基础配置※※※※※※※※※※※※
spring: 
  datasource: #主数据源
    type: 'com.alibaba.druid.pool.DruidDataSource'
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true' #?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
    username: 'root'
    password: '123456'
    #下面为连接池的补充设置，应用到上面所有数据源中
    #初始化大小，最小，最大
    initialSize: 5
    minIdle: 1
    maxActive: 50
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: 'SELECT 1 FROM DUAL'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: 'stat,wall'
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  # MVC 配置
  mvc: 
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
  resources: 
    #不要为我们工程中的资源文件建立映射
    add-mappings: false
  #※※※Ehcache缓存配置※※※
  cache: 
    #配置ehcache缓存名
    type: 'ehcache'
    ehcache: 
      #指定ehcache配置文件路径
      config: 'classpath:ehcache.xml'
  #※※※Redis缓存服务器※※※
  redis: 
    database: 0 #Redis数据库索引（默认为0）
    host: 'localhost' #Redis服务器地址
    port: 6379 #Redis服务器连接端口 
    password: '' #Redis服务器连接密码（默认为空）
    pool: 
      max-active: 200 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接 
    timeout: 1000 #连接超时时间（毫秒）


#※※※※※※※※※※※※Mybatis※※※※※※※※※※※※
mybatis:
  type-aliases-package: com.qm.code.entity
  mapper-locations: 
  - 'classpath:com/qm/frame/mybatis/mapper/**Mapper.xml'
  - 'classpath:com/qm/code/sql/**Mapper.xml'
#※※※※※※※※※※※※Logger※※※※※※※※※※※※
logging:
  config: 'classpath:logback-spring.xml'

#※※※※※※※※※※※※QmFrame※※※※※※※※※※※※
qmframe: 
  #※※※QmSecurityManager※※※
  security: 
    start: false #是否开启权限框架
    secret: sahdwaohxicxzoc #Token秘钥
    requestHeaderTokenKey: token #请求数据时,请求头的tokenkey名
  #※※※请求数据设置※※※
  send: 
    requestDataKey: value #请求数据时，根据该key名解析数据(Rest风格)
    responseDataKey: value #返回数据时，使用的最外层key名(Rest风格)
  #※※※阿里Druid后台监控※※※
  druid: 
    allow: localhost #白名单
    deny: #黑名单
    loginUsername: admin #账号
    loginPassword: 123 #密码
    resetEnable: false #是否可重置数据
  #※※※3DES加密设置※※※
  des3: 
    start: false #是否启用3DES对称加密传输
    key: '2018PinganVitality015522628888ForShenZhenBelter075561869839' #3DES秘钥
    iv: 12101754 #向量  需要8位数字
    encoding: UTF-8 #统一使用的编码方式
  
  #※※※版本控制※※※
  version: 
    start: false #是否开启版本控制(ture时,每个请求需在header带上version参数,参数值version)
    version: '1.0.0' #系统目前版本编号
    permitVersions: #系统容忍请求版本编号(默认允许当前版本)
    - '1.0.1'
    - '1.0.2'
    