#※※※※※※※※※※※※Server※※※※※※※※※※※※
server:
  port: 80
  tomcat: 
      url-encoding: UTF-8
  servlet:
    context-path: #项目路径
#※※※※※※※※※※※※SpringBoot基础配置※※※※※※※※※※※※
spring:
  datasource: #主数据源
    type: 'com.alibaba.druid.pool.DruidDataSource'
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/test'
    username: 'root'
    password: '123'
    #下面为连接池的补充设置，应用到上面所有数据源中
    #初始化大小，最小，最大
    initialSize: 5
    minIdle: 1
    maxActive: 50
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: 'SELECT 1 FROM DUAL'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: 'stat,wall'
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  # MVC 配置
  mvc:
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
  resources: 
    #不要为我们工程中的资源文件建立映射
    add-mappings: false
  #※※※Ehcache缓存配置※※※
  cache: 
    #配置ehcache缓存名
    type: 'ehcache'
    ehcache: 
      #指定ehcache配置文件路径
      config: 'classpath:ehcache.xml'
  #配置thymeleaf 官方推荐模板引擎
  thymeleaf:
    prefix: 'classpath:/views/'
    suffix: '.html'
    mode: 'HTML'
    encoding: 'UTF-8'
    content-type: 'text/html'
    cache: false # 开发阶段务必关闭缓存
  #※※※Redis缓存服务器※※※
  redis: 
    database: 0 #Redis数据库索引（默认为0）
    host: 'localhost' #Redis服务器地址
    port: 6379 #Redis服务器连接端口 
    password: '' #Redis服务器连接密码（默认为空）
    pool: 
      max-active: 200 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接 
    timeout: 1000 #连接超时时间（毫秒）

#※※※※※※※※※※※※Mybatis※※※※※※※※※※※※
mybatis:
  type-aliases-package: com.qm.code.entity # 指定实体类包路径
  mapper-locations:
  - 'classpath*:**/*Mapper.xml' # 该行配置请勿修改
  configuration:
    map-underscore-to-camel-case: false #是否启动数据库下划线自动映射实体
    auto-mapping-behavior: full # resultMap 自动映射级别设置
#※※※※※※※※※※※※Logger※※※※※※※※※※※※
logging:
  config: 'classpath:logback-spring.xml'